seo:
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
cta-shortcode:
  - web-dev
  - photography
